name: publish

on:
  push:
    tags:
      - "**"

jobs:
  publish:
    name: Publish new version to TER
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Publish
        uses: tomasnorre/typo3-upload-ter@wip-version2
        with:
          api-token: ${{ secrets.TYPO3_API_TOKEN }}
